class todoPage():
    Title='/html/body/main/main/h2'
    IdTextField='//*[@id="inputID"]'
    TaskTextField='//*[@id="inputTask"]'
    CreateButton='/html/body/main/main/form/button[1]'
    DeleteButton='/html/body/main/main/form/button[2]'
    UpdateButton='/html/body/main/main/form/button[3]'
    GetButton='/html/body/main/main/form/button[4]'
    DeleteMark='/html/body/main/main/div[1]/button/i'
    CheckMark='/html/body/main/main/div[1]/input'